# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HS_Core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='interval',
            field=models.IntegerField(blank=True, choices=[(1, '1 minuto'), (3, '3 minutos'), (5, '5 minutos'), (10, '10 minutos'), (15, '15 minutos'), (30, '30 minutos')], null=True),
        ),
    ]
