# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HS_Core', '0002_site_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeartBeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('UP', 'Arriba'), ('CONF', 'Conflicto'), ('DOWN', 'Abajo')], max_length=3)),
                ('date', models.DateField(auto_now_add=True)),
                ('responseTime', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'HeartBeat',
                'verbose_name_plural': 'HeartBeats',
            },
        ),
        migrations.RemoveField(
            model_name='hearthbeat',
            name='site',
        ),
        migrations.AlterField(
            model_name='site',
            name='url',
            field=models.CharField(max_length=300),
        ),
        migrations.DeleteModel(
            name='HearthBeat',
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Site', to='HS_Core.Site'),
        ),
    ]
