# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_auto_20170425_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='lastClient',
            new_name='activeClient',
        ),
    ]
