# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_auto_20170426_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='pathToTemplate',
            field=models.CharField(default='a', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
