# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_auto_20170426_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Task',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('tasks', models.ManyToManyField(to='Core.Task')),
            ],
            options={
                'verbose_name': 'Worker',
                'verbose_name_plural': 'Worker',
            },
        ),
    ]
