# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_task_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='workers',
            field=models.ManyToManyField(to='Core.Worker'),
        ),
    ]
