# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_client_workers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tipo',
            new_name='task_type',
        ),
    ]
