# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_auto_20180122_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='percent',
            field=models.CharField(default='0', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('WT', 'En espera'), ('PA', 'Pausado'), ('RU', 'Corriendo'), ('SC', 'Terminado')], default='WT', max_length=300),
        ),
        migrations.AddField(
            model_name='task',
            name='total',
            field=models.CharField(default='0', max_length=50, null=True),
        ),
    ]
