# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_auto_20180122_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('WT', 'En espera'), ('PA', 'Pausado'), ('RU', 'Corriendo'), ('SC', 'Terminado'), ('ER', 'Error')], default='WT', max_length=300),
        ),
    ]
