# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0013_auto_20181021_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apellido',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='correo',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='foto',
            field=models.ImageField(default='default.png', upload_to='user'),
        ),
        migrations.AddField(
            model_name='user',
            name='fumador',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='interes',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='nombre',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='profesion',
            field=models.CharField(default=' ', max_length=30),
        ),
    ]
