# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0016_auto_20181021_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trayecto',
            old_name='id_parada',
            new_name='id_trayecto',
        ),
    ]
