# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0017_auto_20181021_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='parada',
            name='fecha',
            field=models.CharField(default='21/10/18', max_length=30),
        ),
        migrations.AddField(
            model_name='viaje',
            name='fecha',
            field=models.CharField(default='21/10/18', max_length=30),
        ),
        migrations.AddField(
            model_name='viaje',
            name='hora',
            field=models.CharField(default='15:00', max_length=30),
        ),
        migrations.AlterField(
            model_name='parada',
            name='hora',
            field=models.CharField(default='15:00', max_length=30),
        ),
    ]
