# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0018_auto_20181021_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='parada',
            name='nombre',
            field=models.CharField(default='Concepcion', max_length=30),
        ),
        migrations.AddField(
            model_name='viaje',
            name='destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ParadaDestino', to='Core.Parada'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ParadaOrigen', to='Core.Parada'),
        ),
        migrations.AlterField(
            model_name='trayecto',
            name='destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ParadaDestinoTrayecto', to='Core.Parada'),
        ),
        migrations.AlterField(
            model_name='trayecto',
            name='origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ParadaOrigenTrayecto', to='Core.Parada'),
        ),
    ]
