# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0019_auto_20181021_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='trayecto',
            name='plazas',
            field=models.ManyToManyField(to='Core.Plaza'),
        ),
    ]
