# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0020_trayecto_plazas'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='viajes',
            field=models.ManyToManyField(to='Core.Viaje'),
        ),
    ]
