# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0022_demo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField(blank=True, null=True)),
                ('comentario', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Valoracion',
                'verbose_name_plural': 'Valoraciones',
            },
        ),
        migrations.RemoveField(
            model_name='parada',
            name='id_parada',
        ),
        migrations.RemoveField(
            model_name='plaza',
            name='id_plaza',
        ),
        migrations.RemoveField(
            model_name='plaza',
            name='mascota',
        ),
        migrations.RemoveField(
            model_name='trayecto',
            name='id_trayecto',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='hora',
        ),
        migrations.AddField(
            model_name='trayecto',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='celular',
            field=models.IntegerField(default=987654321),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viaje',
            name='estado',
            field=models.IntegerField(default=-1),
        ),
    ]
