# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0023_auto_20181128_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='id_viaje',
        ),
        migrations.AlterField(
            model_name='trayecto',
            name='destino',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ParadaDestinoTrayecto', to='Core.Parada'),
        ),
        migrations.AlterField(
            model_name='trayecto',
            name='origen',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ParadaOrigenTrayecto', to='Core.Parada'),
        ),
        migrations.AlterField(
            model_name='user',
            name='celular',
            field=models.IntegerField(default=123456789),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='destino',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ParadaDestino', to='Core.Parada'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='origen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ParadaOrigen', to='Core.Parada'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='tarifaPreferencias',
            field=models.IntegerField(blank=True, default=100),
        ),
    ]
