# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0024_auto_20181128_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trayectos',
            field=models.ManyToManyField(to='Core.Trayecto'),
        ),
    ]
