# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0025_user_trayectos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='trayectos',
        ),
        migrations.AddField(
            model_name='trayecto',
            name='viaje',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Viaje', to='Core.Viaje'),
        ),
    ]
