# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0026_auto_20181128_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='viajes',
            field=models.ManyToManyField(null=True, to='Core.Viaje'),
        ),
    ]
