# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-29 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0030_auto_20181128_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='trayecto',
            name='distancia',
            field=models.IntegerField(default=100),
        ),
    ]
