# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-29 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0031_trayecto_distancia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trayecto',
            name='distancia',
        ),
        migrations.AddField(
            model_name='viaje',
            name='precio',
            field=models.IntegerField(default=100),
        ),
    ]
