# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-29 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0032_auto_20181129_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parada',
            name='coordenada_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parada',
            name='coordenada_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parada',
            name='fecha',
            field=models.CharField(default='2018/11/12', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='trayectos',
            field=models.ManyToManyField(related_name='user', to='Core.Trayecto'),
        ),
    ]
