# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-03 01:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0033_auto_20181129_0336'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Demo',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='client',
            name='workers',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
