# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-03 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0034_auto_20181202_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='plazas_max',
            field=models.IntegerField(default=4),
        ),
    ]
