# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-20 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0035_viaje_plazas_max'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_plazas', models.IntegerField(default=4)),
                ('maletero', models.BooleanField(default=True)),
                ('mascota', models.BooleanField(default=True)),
                ('silla_ninnos', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Prestacion',
                'verbose_name_plural': 'Prestaciones',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.IntegerField(blank=True, null=True)),
                ('estado', models.IntegerField(default=-1)),
            ],
            options={
                'verbose_name': 'Plazas',
                'verbose_name_plural': 'Plazas',
            },
        ),
        migrations.CreateModel(
            name='Tramo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km', models.IntegerField(blank=True, null=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('destino', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ParadaDestinoTramo', to='Core.Parada')),
                ('origen', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ParadaOrigenTramo', to='Core.Parada')),
                ('plazas', models.ManyToManyField(to='Core.Plaza')),
                ('viaje', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ViajeTramo', to='Core.Viaje')),
            ],
            options={
                'verbose_name': 'Trayecto',
                'verbose_name_plural': 'Trayectos',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('foto_vehiculo', models.ImageField(upload_to='autos')),
                ('color', models.CharField(max_length=15)),
                ('anno', models.IntegerField(blank=True, default=1800, null=True)),
                ('numero_asientos', models.IntegerField(blank=True, default=4, null=True)),
                ('precio_combustible', models.IntegerField(blank=True, default=30, null=True)),
            ],
            options={
                'verbose_name': 'Vehiculo',
                'verbose_name_plural': 'Vehiculos',
            },
        ),
        migrations.AddField(
            model_name='reserva',
            name='tramo',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Tramo', to='Core.Tramo'),
        ),
        migrations.AddField(
            model_name='user',
            name='reserva',
            field=models.ManyToManyField(related_name='user', to='Core.Reserva'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='prestacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Prestacion', to='Core.Prestacion'),
        ),
    ]
