# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-21 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0036_auto_20190520_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='viaje',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ViajeReserva', to='Core.Viaje'),
        ),
    ]
