# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-21 21:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0037_reserva_viaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramo',
            name='plazas',
        ),
    ]
