# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-21 21:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0038_remove_tramo_plazas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='reserva',
            new_name='reservas',
        ),
    ]
