# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-21 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0039_auto_20190521_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='precio',
        ),
    ]
