# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-21 22:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0040_remove_viaje_precio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tramo',
            options={'verbose_name': 'Tramo', 'verbose_name_plural': 'Tramos'},
        ),
    ]
