# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-22 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0042_auto_20190522_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trayecto',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='trayecto',
            name='origen',
        ),
        migrations.RemoveField(
            model_name='trayecto',
            name='plazas',
        ),
        migrations.RemoveField(
            model_name='trayecto',
            name='viaje',
        ),
        migrations.RemoveField(
            model_name='conductor',
            name='foto_vehiculo',
        ),
        migrations.RemoveField(
            model_name='conductor',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='conductor',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='trayectos',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='maletero',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='mascota',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='plazas_max',
        ),
        migrations.DeleteModel(
            name='Plaza',
        ),
        migrations.DeleteModel(
            name='Trayecto',
        ),
    ]
