# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-27 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0043_auto_20190522_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='valoraciones',
            field=models.ManyToManyField(related_name='user', to='Core.Valoracion'),
        ),
    ]
