# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-27 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0046_user_valoraciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='promedioVal',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
