# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-10 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0047_user_promedioval'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='vehiculo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Vehiculo', to='Core.Vehiculo'),
        ),
    ]
