# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-09 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0049_auto_20190709_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parada',
            name='fecha',
            field=models.CharField(default='2018/11/12', max_length=30),
        ),
        migrations.AlterField(
            model_name='parada',
            name='hora',
            field=models.CharField(default='15:00', max_length=30),
        ),
    ]
