# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-10 01:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0051_auto_20190709_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='valoracion',
            name='usuario',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
