# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-17 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VIM_Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='finishDate',
            field=models.DateTimeField(default='', max_length=15, null=True),
        ),
    ]
