# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-17 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VIM_Core', '0004_auto_20180117_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='startDate',
            field=models.DateTimeField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='status',
            field=models.CharField(choices=[('WT', 'En espera'), ('PA', 'Pausado'), ('RU', 'Corriendo'), ('RU', 'Terminado')], default='WT', max_length=300),
        ),
    ]
