# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VIM_Core', '0007_auto_20180117_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='asset',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ASE_Core.Asset'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='assets',
            field=models.ManyToManyField(to='ASE_Core.Asset'),
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
    ]
