# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VIM_Core', '0008_auto_20180118_1145'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Picture',
            new_name='Finding',
        ),
        migrations.AlterModelOptions(
            name='finding',
            options={'verbose_name': 'Finding', 'verbose_name_plural': 'Findings'},
        ),
    ]
