# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VIM_Core', '0009_auto_20180118_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='startDate',
            field=models.DateTimeField(auto_now_add=True, max_length=15, null=True),
        ),
    ]
