# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VIM_Core', '0010_auto_20180119_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='name',
            field=models.CharField(default='0', max_length=50, null=True),
        ),
    ]
