# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-29 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0012_task_previus_id'),
        ('ASE_Core', '0006_auto_20180129_1252'),
        ('VIM_Core', '0012_auto_20180122_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finding',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='idTask',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='percent',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='status',
        ),
        migrations.AddField(
            model_name='finding',
            name='url',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finding', to='ASE_Core.Url'),
        ),
        migrations.AddField(
            model_name='scan',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.Task'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='scan',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='VIM_Core.Scan'),
        ),
    ]
