# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VIM_Core', '0014_auto_20180129_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='url',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
