# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VIM_Core', '0017_auto_20180131_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='asset',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finding_vim', to='ASE_Core.Asset'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='scan',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='findings_vim', to='VIM_Core.Scan'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='proxyFtp',
            field=models.CharField(blank=True, default='-1', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='proxyFtpPort',
            field=models.CharField(blank=True, default='-1', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='proxyHttp',
            field=models.CharField(blank=True, default='-1', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='proxyHttpPort',
            field=models.CharField(blank=True, default='-1', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='proxySocks',
            field=models.CharField(blank=True, default='-1', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='proxySocksPort',
            field=models.CharField(blank=True, default='-1', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='proxySsl',
            field=models.CharField(blank=True, default='-1', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='proxySslPort',
            field=models.CharField(blank=True, default='-1', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan', to='Core.Task'),
        ),
    ]
