# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VIM_Core', '0018_auto_20180131_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='asset',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vim_finding', to='ASE_Core.Asset'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='scan',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='vim_finding', to='VIM_Core.Scan'),
        ),
    ]
