# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-13 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=15)),
                ('comment', models.CharField(max_length=15)),
                ('files', models.CharField(max_length=15)),
                ('date', models.CharField(max_length=15)),
                ('forwarder', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_petition', models.CharField(max_length=15)),
                ('id_workOrder', models.CharField(max_length=15)),
                ('client', models.CharField(max_length=15)),
                ('resume', models.CharField(max_length=15)),
                ('notes', models.CharField(max_length=15)),
                ('user_asigned', models.CharField(max_length=15)),
                ('group_asigned', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=15)),
                ('status_cause', models.CharField(max_length=15)),
                ('status_note', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
    ]
