# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-13 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WM_Core', '0002_auto_20170913_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following',
            name='service',
        ),
        migrations.AddField(
            model_name='following',
            name='comment',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='ticket',
            name='created',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='ticket',
            name='services',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
