# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-15 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WM_Core', '0004_auto_20170915_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='client',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='notes',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='resume',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='services',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status_cause',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status_note',
            field=models.CharField(max_length=500),
        ),
    ]
