# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-15 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WM_Core', '0005_auto_20170915_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
