# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-15 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WM_Core', '0006_auto_20170915_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='services',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
