# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WM_Core', '0007_auto_20170915_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='following',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='following',
            name='ticket',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='WM_Core.Ticket'),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
