# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WM_Core', '0009_auto_20170920_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inbox',
            old_name='date',
            new_name='date_in',
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='forwarder',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='inbox_active',
        ),
        migrations.AddField(
            model_name='inbox',
            name='date_out',
            field=models.CharField(default='', max_length=15, null=True),
        ),
    ]
