# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-22 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WM_Core', '0010_auto_20170920_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='date_in',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='date_out',
            field=models.DateTimeField(null=True),
        ),
    ]
