# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-25 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WM_Core', '0011_auto_20170922_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='date_in',
            field=models.DateTimeField(null=True),
        ),
    ]
