# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-25 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WM_Core', '0012_auto_20170925_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
