# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-18 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WM_Core', '0015_auto_20171018_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='ticket',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='WM_Core.Ticket'),
        ),
    ]
