# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-18 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WM_Core', '0016_auto_20171018_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='following',
            name='wo',
            field=models.CharField(default='', max_length=15),
        ),
    ]
