# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-19 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WM_Core', '0017_following_wo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='services',
        ),
        migrations.AddField(
            model_name='following',
            name='services',
            field=models.CharField(choices=[('VM', 'Vulnerabilidades'), ('TM', 'Amenazas'), ('CM', 'Certificados')], max_length=50, null=True),
        ),
    ]
