# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-19 16:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WM_Core', '0018_auto_20171019_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='', max_length=15)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='WM_Core.Ticket')),
            ],
            options={
                'verbose_name': 'Comentary',
                'verbose_name_plural': 'Comentaries',
            },
        ),
        migrations.RemoveField(
            model_name='following',
            name='comment',
        ),
    ]
