# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-19 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WM_Core', '0019_auto_20171019_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='following',
            old_name='services',
            new_name='service',
        ),
    ]
