# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-31 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WM_Core', '0020_auto_20171019_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentary',
            name='comment',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='detail',
            name='date',
            field=models.DateTimeField(default='', max_length=15),
        ),
    ]
