# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-07 21:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WM_Core', '0021_auto_20171031_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escalation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(default='', max_length=300)),
                ('recipient', models.CharField(default='', max_length=300)),
                ('comment', models.CharField(default='', max_length=300)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='WM_Core.Ticket')),
            ],
            options={
                'verbose_name': 'Escalation',
                'verbose_name_plural': 'Escalations',
            },
        ),
        migrations.AlterField(
            model_name='following',
            name='service',
            field=models.CharField(choices=[('VM', 'Vulnerabilidades'), ('TM', 'Amenazas'), ('CM', 'Certificados'), ('IN', 'Incidentes'), ('EV', 'Eventos'), ('HD', 'Hardening'), ('PC', 'Parches'), ('GC', 'Gestion CCI'), ('ID', 'Gestion Identidades')], max_length=50, null=True),
        ),
    ]
