# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-07 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WM_Core', '0022_auto_20171107_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalation',
            name='method',
            field=models.CharField(choices=[('TL', 'Telefono'), ('EM', 'Email'), ('PP', 'En Persona')], default='', max_length=300),
        ),
    ]
