# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-14 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WM_Core', '0023_auto_20171107_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='following',
            name='company',
            field=models.CharField(choices=[('CGE', 'CGE'), ('MTG', 'MetroGas'), ('CGT-MTG', 'CGE-MetroGas')], max_length=50, null=True),
        ),
    ]
