# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ASE_Core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='assets',
            new_name='asset',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='codigo',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='url',
            old_name='assets',
            new_name='asset',
        ),
    ]
