# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASE_Core', '0002_auto_20180118_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='url',
            name='asset',
        ),
        migrations.AddField(
            model_name='asset',
            name='tag',
            field=models.ManyToManyField(to='ASE_Core.Tag'),
        ),
        migrations.AddField(
            model_name='asset',
            name='url',
            field=models.ManyToManyField(to='ASE_Core.Url'),
        ),
    ]
