# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASE_Core', '0003_auto_20180118_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='ASE_Core.Tag'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='url',
            field=models.ManyToManyField(blank=True, null=True, to='ASE_Core.Url'),
        ),
    ]
