# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ASE_Core', '0004_auto_20180125_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='url',
        ),
        migrations.AddField(
            model_name='tag',
            name='asset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ASE_Core.Asset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url',
            name='asset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ASE_Core.Asset'),
            preserve_default=False,
        ),
    ]
