# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-29 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ASE_Core', '0005_auto_20180125_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='ASE_Core.Asset'),
        ),
        migrations.AlterField(
            model_name='url',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='ASE_Core.Asset'),
        ),
    ]
