# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-29 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ASE_Core', '0007_auto_20180129_1741'),
        ('VIM_Core', '0014_auto_20180129_1741'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Url',
        ),
    ]
