# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASE_Core', '0008_delete_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='assets',
            field=models.ManyToManyField(blank=True, related_name='Tags', to='ASE_Core.Asset'),
        ),
    ]
