# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASE_Core', '0009_auto_20180130_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='assets',
        ),
        migrations.AddField(
            model_name='asset',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='Assets', to='ASE_Core.Tag'),
        ),
    ]
